### ISSUE TITLE
Multiple map functions breaks syntax highlighting

### ISSUE THREAD

**Issue by adamjohnson** [SublimeText/Astro#1] opened 2022-07-11 16:59 UTC
![Example of broken syntax highlighting in a Review Astro component](https://user-images.githubusercontent.com/575865/178317163-ac3f3755-3dda-40c5-ac34-da4cabc3eef8.png)

You can see the code for this component at [this Github repo](https://github.com/coding-in-public/desgn-landing-page/blob/main/src/components/Reviews.astro).

I see this a lot in my projects where my files have 50-100+ lines of code. 

FWIW, I am running ST v4126 with the Astro v2.0.0 extension. Happy to provide any other info upon request.

**Comment by deathaxe** [comment] 2022-08-13 10:01
The issue is caused by https://github.com/sublimehq/Packages/issues/3473

**Comment by deathaxe** [comment] 2022-08-14 08:24
By using strictly valid JSX syntax the issue could be worked around.

Default JSX/TSX requires `<img />` to be a self-closing tag. It wouldn't compile otherwise.

**Comment by adamjohnson** [comment] 2022-08-29 16:02
Can confirm, adding a closing slash to the `<img />` tags on lines 16, 25, and 34 fixes the issue in this file.

I will endeavor to include closing slashes for self closing tags (eg `<br />`, `<img />`, `<hr />`, etc). Thanks for your insight. 👍

**Closed as completed** 2023-01-21 11:20 UTC
